    global:
      # slack_api_url: ''
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: 'honglei248@163.com'
      smtp_auth_username: 'honglei248@163.com'
      smtp_auth_password: 'XXXXXXXX'
      smtp_require_tls: false
    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
    receivers:
    - name: default-receiver
      email_configs:
      - to: '226596391@qq.com'

